import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'react-toastify/dist/ReactToastify.css';
import './globals.css'
import Navbar from '@comp/Navbar'
import { ToastContainer } from 'react-toastify'
import { Providers } from './redux/provider';
import { ThemeProvider } from './theme-provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Modern Blog',
  description: 'Generated by Rasoul Jabbari',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' dark:bg-gray-800 bg-white'}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <div className="space-y-4 md:space-y-8">
              <Navbar />
              <div className="container mx-auto px-4">
                {children}
              </div>
              <ToastContainer
                position="top-center"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
